### ISSUE TITLE
Question about 1.0.1 changes

### ISSUE THREAD

**Issue by Baalvon** [Joegenco/PixelManager#17]
About the changes in the 1.0.1 build 46b5a75fd3af0c8e3440f33d021612a325bc1c4b

Why only change the vendor looks but not AgX base and AgX Resolve looks from sRGB to EOTF 2.2?

Also maybe some small mistakes in the code:
1. [Line 1675:](https://github.com/Joegenco/PixelManager/blob/master/config.ocio?plain=1#L1675) it's still sRGB.
2. [Line 2095:](https://github.com/Joegenco/PixelManager/blob/master/config.ocio?plain=1#L2095) "Utility - Gamma 2.2 - Rec.709 - Texture" was incompletely deleted, now it's "g22_rec709 - Texture".

**Comment by Joegenco** [comment]
Objective is to match the "intended" look of vendor files.

AgX'es intended look in Eary's config (which is used in Blender 4.0) is with a piecewise function (current sRGB)
Whereas vendor's already apply a "toe" within their luts which results in different values when going from BT1886 to "sRGB" with a piecewise function. Recently discovered this messing around in DaVinci with vendor luts, now it gives the expected result with a pure gamma.


-----
1. Similarly this is ACES'es "intended" look. It yields matching results with a defult ACES config.
2. Yes, this is a typo. Will be fixed in the next version, this "alias" made this colorspace feel like its pure EOTF which its not.

----

The Piecewise function vs pure gamma is a bit funky and I am not sure how to "make it right" since Pure gamma is the right way to do it, but default AgX (for blender) and ACES uses piecewise function. Whereas AgX(Kraken) uses pure gamma, alongside vendors luts pulling back down to sRGB with pure gamma too. I will have a think about it.

Leaving the issue open until 1.1.0 release.

**Comment by Baalvon** [comment]
Understood, thank you. I've read about the piecewise vs pure gamma debate, and I believe encoding with pure gamma 2.2 generally yields better results too.

The "offset within vendor luts" is very interesting, do you mind elaborate on that discovery? In my opinion, the only intended EOTF of the vendor luts are written in their names, mostly pure gamma 2.4, as the look was color graded in that environment, for that environment.

**Comment by Joegenco** [comment]
About the "gamma", this seems to be a bit ellusive subject which I also dont have a full grip on because there are standards on standards...

Idea is to match the inverse gamma that the display applies right?

Production/grading monitors use pure 2.4 gamma for BT1886 / Rec709 format. So it makes sense that LUTs that the vendors provide is that.

So how are we supposed to look at these in our "consumer" sRGB monitors? Consumer displays have a variety of querkyness going on in them. For now lets put the "gamut" aside since its a whole different beast. If I want to see the 2.4 gamma LUT the vendor provides on my sRGB monitor, I'd want to go from 2.4 gamma to 2.2 gamma.

Im about to spam some images now, save them to compare more directly if you wish.
--------

Going back to the testing and what I spotted:
This is ARRI K1S1 without any changes. Expected output is 2.4 gamma.
![image](https://github.com/Joegenco/PixelManager/assets/33637910/fadd7e32-4fe1-4ed7-a962-927106d766ea)

This is the same image formation but going from 2.4 gamma to "sRGB" with a piecewise function. (Like it was in 1.0.0)
Look at the low end, since the piecewise function for sRGB is defined with a 2.4 gamma but with 0.055 offset like 
`        - !<ExponentWithLinearTransform> {gamma: 2.4, offset: 0.055, direction: inverse} `
We end up clipping the lower end.
![image](https://github.com/Joegenco/PixelManager/assets/33637910/4e8f1653-63b8-4e29-8990-7c1e68518d16)


And here it is going from 2.4 gamma to "pure 2.2 gamma" (like it is in 1.0.1)
Which seems to be the right way to pull this image to an "sRGB" monitor.
![image](https://github.com/Joegenco/PixelManager/assets/33637910/7d9c9958-72c5-47e8-8c2c-9118143c906e)

---------

After doing some digging.... Monitor "standards" are awful. And pure 2.2 gamma is defined as sRGB but there is more to it with flare compensation etc... Found this [webinar by filmlight ](https://www.youtube.com/watch?v=NzhUzeNUBuM)which I will consume and do some more digging.

I might end up removing ALL piecewise crap and only using pure gamma for the whole config, including the textures... More to come..

**Comment by Baalvon** [comment]
Thanks again for the detailed reply. I've done the exact research recently, based on that [sRGB essay by Filmlight](https://www.youtube.com/watch?v=NzhUzeNUBuM) and this [heated sRGB dicussion](https://community.acescentral.com/t/srgb-piece-wise-eotf-vs-pure-gamma/4024l).

My biggest takeaway regarding (vendor) looks for 2.2 display is this: 

**Vendor looks made for 2.4 Gamma environment should NOT be simply re-encoded to Gamma 2.2.** The perfect yet impractical way to make them work for 2.2 display is letting the original colorist specifically adjust the look with their original grading tools with a 2.2 monitor in a 2.2 enviroment. Otherwise, in real life, just use the original 2.4 LUT on a 2.2 display **as is**.

The reason is:

sRGB or pure power law 2.2 environmnet is presumed to be well lit. But simply re-encode 2.4 looks to 2.2 makes the image darker, which is opposite how 2.2 images should look like. [According to Daniele](https://youtu.be/NzhUzeNUBuM?si=brCOPPnyiTeCHf_M&t=1916) in that Filmlight sRGB essay, the best way to do this is grading the LUT with bright surround compensation before encoding it with 2.2 gamma. For our vendor look scenario, this is unrealistic, because most users lack the technical and artistic basis to correctly adjust the vendor looks.

[Daniele points out](https://youtu.be/NzhUzeNUBuM?si=VuLAQIZrYf63OtLU&t=1502) another way that people have been widely using, simply use 2.4 LUT on 2.2 displays as is, utilizing the gamma unmatch as bright surround compensation. The unmatched gamma creates flaws like slight color skew etc., but I think it will still look better than the darkened image that the simple 2.2 re-encoding creates.

The goal is to give a majority of audience a better viewing experience while preserving the vendor LUTs' artistic vision as much as possible.

**Comment by Joegenco** [comment]
A head scratcher this one. Ill get back to discussion/work on this soon.

**Comment by Joegenco** [comment]
Okay, now in the latest we call piecewise gamma "legacy" and everything now uses pure power function instead.

2.4 dim vs 2.2 bright is somewhat of an unsolveable issue.

Rigth now:
BT.1886 display uses the image formers designed for dim surround 2.4, except AgX, OpenDRT, JZDT.
sRGB display uses image formers designed for bright surround, except the vendor looks (they also have 2.4 to 2.2 power function applied)

A solution might be:
Split all Displays to dim and bright versions and only include whats appropriate in there.

I really like the demonstration that Danielle makes with the 2.4 being viewed in bright condition with 2.2 inverse function. It really magically matches near perfectly. But this is somewhat of a trickery. 
Yet again, when delivering to "casual" medium environments change drastically since %90 people watch on their phones in various environmnets.

**Comment by Baalvon** [comment]
I've been thinking and testing about this. I stand by my point that 2.4 looks as bright environment compensation works well for 2.2 devices. However, I'm not sure if converting 2.4 look to 2.2 gamma is wrong like I thought.

Practically speaking, for my own video content, I'll just use 2.4 LUT, as most viewers on Youtube, Instagram etc. like slightly brighter image. And being a perfectionist of color grading is pointless for web content because most viewers have things like anti-blue light / night mode, dynamic color temperature adjustment etc. on on their phones or laptop monitors.

Regarding the solution, If I were to maintain the project, I would just leave it as what it is right now. Let the people who know what they are doing choose between the original 2.4 vendor LUT and the converted 2.2 one. Otherwise, the OCIO menu would probably be very convoluted and confusing.

I have no more issues and nothing to add on this topic. Thank you for your time.

**Comment by Joegenco** [comment]
Latest update fixes the power function by using pure power across the board. Piecewise power is now named legacy for compatabilitys sake.

It does not adress the dim vs bright topic. In the future i might seperate the "display device" and include the environment as a context in there.

Thank you for your help!
