### ISSUE TITLE
Change Rec709 EOTF 2.2 "ExponentWithLinearTransform" to "ExponentTransform"

### ISSUE THREAD

**Issue by joelRVC** [Joegenco/PixelManager#19]
There was a issue in blender a few months ago in which ExponentWithLinearTransform with offset 0 caused errors on some Apple gpus, it was fixed using ExponentTransform. Since the EOTF 2.2 power law does not define an offset it would be good to make this change mainly to make sure there are no problems (I can't test it myself since I don't use apple products, but I think it would help). By the way, you could also update the description of that function, it still mentions srgb as piecewise.

The blender report in case you need to take a look: https://projects.blender.org/blender/blender/pulls/114853

**Comment by joelRVC** [comment]
Taking a better look at the config file of the main branch I see that there are actually several functions and color spaces that need that change.

**Comment by Joegenco** [comment]
I'm out on a shoot this week. I'll go over the suggestions moment I'm back.

I want to rethink the way the "gamma" of displays are for the config
anyway. I was strictly trying to follow parity with Blender Default and
ACES configs since they use "two part" power function which is not "pure
2.2" but this is wrong and opposed to what most if not all display
manufacturers do. So time to fix this crap!

Thank you!
