### ISSUE TITLE
PBRMaps Regex is ignored

### ISSUE THREAD

**Issue by Hopefullyidontgetbanned** [Joegenco/PixelManager#3]
file rules for importing images with certain suffixes is completely ignored, defeating the point, it simply defaults to srgb, I used a regex tester and it should work but it just doesn't. Blender logs show nothing
Blender 3.6.1, Windows 11, RTX 4070,Nvidia GeForce Gameready driver (I doubt this has any relevance)

**Comment by Joegenco** [comment]
Yeah, this one is due to blenders use of OCIO I'm afraid. Regex with OCIO is rarely fully supported. With Maya it somewhat works.

I have not taken it to Blender Devs tho. I think there's quite a few QOL improvements needed to implentation of OCIO in blender before they get to Regex rules.

Appricate the feedback! Please let me know if you spot anything else.
